// <auto-generated />
using Labb4_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb4_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230507184304_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb4_API.Models.Hobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Creating software with computer languages.",
                            Title = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Racing other people often at 200m races.",
                            Title = "Running"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Catch fish's from a body of water.",
                            Title = "Fishing"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Building webbsites with virtual lego (html).",
                            Title = "Webbdevelopment"
                        });
                });

            modelBuilder.Entity("Labb4_API.Models.LinksHobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HobbiesId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HobbiesId");

                    b.HasIndex("PersonId");

                    b.ToTable("LinksHobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HobbiesId = 1,
                            Link = "www.github.com",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            HobbiesId = 2,
                            Link = "www.github.com/lucas-ohlin",
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            HobbiesId = 3,
                            Link = "www.lures.com",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 4,
                            HobbiesId = 4,
                            Link = "www.w3schools.com",
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            HobbiesId = 3,
                            Link = "www.fishing.com",
                            PersonId = 3
                        });
                });

            modelBuilder.Entity("Labb4_API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lucas",
                            Number = "123123123"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Edvin",
                            Number = "3459128"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Emil",
                            Number = "7777777"
                        });
                });

            modelBuilder.Entity("Labb4_API.Models.LinksHobbies", b =>
                {
                    b.HasOne("Labb4_API.Models.Hobbies", "Hobbies")
                        .WithMany("LinksPerson")
                        .HasForeignKey("HobbiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb4_API.Models.Person", "Person")
                        .WithMany("LinksHobbies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hobbies");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb4_API.Models.Hobbies", b =>
                {
                    b.Navigation("LinksPerson");
                });

            modelBuilder.Entity("Labb4_API.Models.Person", b =>
                {
                    b.Navigation("LinksHobbies");
                });
#pragma warning restore 612, 618
        }
    }
}
